[package]
name = "auth-spec-checks"
version = "0.0.0"
authors = ["Mark Achee <mark@achee.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
serde_json = "1"
tokio = { version = "0.2", features = ["full"] }
